### ISSUE TITLE
The dataset is invalid, can you provide it again?

### ISSUE THREAD

**Issue by Faker0715** [Walid-khaled/Design-Patterns-Detection-ML#1]
thank you very much!
wangkunfangzhe@gmail.com

**Comment by Walid-khaled** [comment]
Hello, you can check the repo now.

https://drive.google.com/drive/folders/1ETJl9cxjPJKbpqYCO40kHxoUg5XqboPt?usp=sharing



Regards,

Walid Khaled

Robotics Software Engineer at Innopolis Autonomous Technologies Lab

MSc student in Robotics and Computer Vision at Innopolis University<https://innopolis.university/en/>

BSc in Mechatronics Engineering at Nile University<https://www.nu.edu.eg/index.php>, Egypt

Founder of RPM Student Organization<https://www.facebook.com/RPMNU/>, Nile University, Egypt



________________________________
From: Faker ***@***.***>
Sent: Sunday, July 10, 2022 4:26 AM
To: Walid-khaled/Design-Patterns-Detection-ML ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Walid-khaled/Design-Patterns-Detection-ML] The dataset is invalid, can you provide it again? (Issue #1)


thank you very much!
***@***.******@***.***>

**Comment by Faker0715** [comment]
sorry，i meet 404 to go this website. can you send again? thank you very much!

**Comment by alles2** [comment]
Hi, i found this work very interesting, i would also like to have access to the dataset!!

**Comment by Walid-khaled** [comment]
Hello, did you check Dp_data folder ? https://github.com/Walid-khaled/Design-Patterns-Detection-ML/tree/main/Dp_data
________________________________
